version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: education_platform
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./sql/init.sh:/docker-entrypoint-initdb.d/init.sh
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
    ports:
      - "9000:9000"    # S3 API
      - "9001:9001"    # MinIO Console
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network

volumes:
  mysql-data:
  minio-data:

networks:
  app-network:
