services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: education_platform
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./sql/init.sh:/docker-entrypoint-initdb.d/init.sh
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  logic_app:  # 定義應用邏輯服務
    build: ./logic_app  # 指定 Dockerfile 路徑來構建應用映像
    container_name: logic_app  # 指定容器名稱為 logic_app
    volumes:  # 定義數據掛載點
      - ./logic_app:/app  # 將本地應用代碼掛載到容器中的 /app 目錄
    ports:
      - "5001:5000"  # 將主機的 5001 端口映射到容器的 5000 端口
    networks:
      - app_network  # 指定容器所屬的網絡

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   restart: always
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: adminpassword
  #   ports:
  #     - "9000:9000"    # S3 API
  #     - "9001:9001"    # MinIO Console
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio-data:/data
  #   networks:
  #     - app-network

volumes:
  mysql_data:

networks:
  app_network:
